-- 第一次テスト、名無しユーザでもinsert可能に
alter table public.thinks enable row level security;
create policy "Allow anonymous inserts" on public.thinks
  for insert
    to anon
    with check (true);
-- 第二次テスト、名無しユーザでもselect可能に
create policy "Allow anonymous reads"
on public.thinks
    for select
    to anon
    using (true);

-- 第三次テスト、Discuss用のテーブルrepliesテーブルを追加
create table public.replies (
    id bigint generated by default as identity primary key,
    think_id uuid not null references public.thinks(id) on delete cascade,
    text text not null
        check (char_length(trim(text)) > 0),
    created_at timestamptz not null default now()
);

create index replies_think_id_created_at_idx
    on public.replies (think_id, created_at);
alter table public.replies enable row level security;

create policy "Allow anonymous inserts" on public.replies
    for insert
        to anon
        with check (true);

create policy "Allow anonymous reads" on public.replies
    for select
        to anon
        using (true);

-- 第四次テスト、knowledge用のテーブルknowledgeテーブルを追加
create table public.knowledge (
    id bigint generated by default as identity primary key,
    think_id uuid not null unique references public.thinks(id) on delete cascade,
    summary text not null check (char_length(trim(summary)) > 0),
    common_points text,
    disagreements text,
    open_questions text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.knowledge enable row level security;

create policy "Allow anonymous knowledge inserts" on public.knowledge
    for insert
        to anon
        with check (true);

create policy "Allow anonymous knowledge select" on public.knowledge
    for select
        to anon
        using (true);

create policy "Allow anonymous knowledge update" on public.knowledge
    for update
        to anon
        using (true)
        with check (true);

-- 第五次テスト、全てのテーブルポリシーにauthenticatedを許可。
-- Insert ー＞　Auth　Select -> AnonとAuth 

-- Thinksテーブルのポリシー編集
alter policy "Allow anonymous inserts"
    on public.thinks
        to authenticated
        with check (true);

alter policy "Allow anonymous reads"
    on public.thinks
        to anon, authenticated
        using(true);

-- Repliesテーブルのポリシー編集
alter policy "Allow anonymous inserts"
    on public.replies
        to authenticated
        with check(true);

alter policy "Allow anonymous reads"
    on public.replies
        to anon, authenticated
        using(true);

-- Knowledgeテーブルのポリシー編集
alter policy "Allow anonymous knowledge inserts"
    on public.knowledge
        to authenticated
        with check(true);

alter policy "Allow anonymous knowledge select"
    on public.knowledge
        to anon, authenticated
        using(true);

alter policy "Allow anonymous knowledge update"
    on public.knowledge
        to authenticated
        with check(true);

-- 第六次テスト、各自テーブルの引数追加
-- thinksテーブルで引数追加
alter table public.thinks
    add column if not exists user_id uuid
        references auth.users(id) on delete cascade,
    add column if not exists is_public boolean
        not null default true;

-- repliesテーブルで引数追加
alter table public.replies
    add column if not exists user_id uuid 
        references auth.users(id) on delete cascade;


-- 第7次テスト、各自テーブル・ポリシー追加

-- thinksテーブルにuser_id用のポリシー作成
alter policy "Allow anonymous inserts" on public.thinks
    to  authenticated
    with check(
        (select auth.uid()) = user_id
    );

alter policy "Allow anonymous reads" on public.thinks
    to anon, authenticated
    using(
        is_public = true 
         or user_id = (select auth.uid())
    );

-- repliesテーブルにuser_id用のポリシー作成

alter policy "Allow anonymous inserts" on public.replies
    to authenticated
    with check(
        (select auth.uid()) = replies.user_id
        
        and

        exists (
            select 1
            from public.thinks as think
            where think.id = replies.think_id
                and (
                    think.is_public = true
                    or think.user_id = (select auth.uid())
                )
        )
    );

alter policy "Allow anonymous reads" on public.replies
    to anon, authenticated
    using(
        exists (
            select 1
            from public.thinks as think
            where think.id = replies.think_id
                and (
                    think.is_public = true
                    or think.user_id = (select auth.uid())
                )
        )
    );

-- Knowledgeテーブル
alter policy "Allow anonymous knowledge inserts" on public.knowledge
    to authenticated
    with check(
        exists(
            select 1 
            from public.thinks as think
            where think.id = knowledge.think_id
                and think.user_id = (select auth.uid())
        )
    );

alter policy "Allow anonymous knowledge select" on public.knowledge
    to anon, authenticated
    using(
        exists (
            select 1
            from public.thinks as think
            where think.id = knowledge.think_id
                and (
                    think.is_public = true
                    or think.user_id = (select auth.uid())
                )
        )
    );

alter policy "Allow anonymous knowledge update" on public.knowledge
    to authenticated
    using(
        exists(
            select 1
            from public.thinks as think
            where think.id = knowledge.think_id
                and think.user_id = (select auth.uid())
        )
    )
    with check(
        exists(
            select 1
            from public.thinks as think
            where think.id = knowledge.think_id
                and think.user_id = (select auth.uid())
        )
    );


-- thinks・repliesテーブルのuser_idに権限追加
-- 今の設定だと、user_idにauth.uid()が自動設定されない。

-- --　一旦、user_idの既存データを削除する。
-- delete from public.thinks  where user_id is null;
-- delete from public.replies where user_id is null;

-- thinksテーブルのuser_idにauth.uid()をデフォで追加させる。
alter table public.thinks
    alter column user_id set default auth.uid(),
    alter column user_id set not null;

-- repliesテーブルも同様に
alter table public.replies
    alter column user_id set default auth.uid(),
    alter column user_id set not null;
