-- 第一次テスト、名無しユーザでもinsert可能に
alter table public.thinks enable row level security;
create policy "Allow anonymous inserts" on public.thinks
  for insert
    to anon
    with check (true);
-- 第二次テスト、名無しユーザでもselect可能に
create policy "Allow anonymous reads"
on public.thinks
    for select
    to anon
    using (true);

-- 第三次テスト、Discuss用のテーブルrepliesテーブルを追加
create table public.replies (
    id bigint generated by default as identity primary key,
    think_id uuid not null references public.thinks(id) on delete cascade,
    text text not null
        check (char_length(trim(text)) > 0),
    created_at timestamptz not null default now()
);

create index replies_think_id_created_at_idx
    on public.replies (think_id, created_at);
alter table public.replies enable row level security;

create policy "Allow anonymous inserts" on public.replies
    for insert
        to anon
        with check (true);

create policy "Allow anonymous reads" on public.replies
    for select
        to anon
        using (true);

-- 第四次テスト、knowledge用のテーブルknowledgeテーブルを追加
create table public.knowledge (
    id bigint generated by default as identity primary key,
    think_id uuid not null unique references public.thinks(id) on delete cascade,
    summary text not null check (char_length(trim(summary)) > 0),
    common_points text,
    disagreements text,
    open_questions text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.knowledge enable row level security;

create policy "Allow anonymous knowledge inserts" on public.knowledge
    for insert
        to anon
        with check (true);

create policy "Allow anonymous knowledge select" on public.knowledge
    for select
        to anon
        using (true);

create policy "Allow anonymous knowledge update" on public.knowledge
    for update
        to anon
        using (true)
        with check (true);

-- 第五次テスト、全てのテーブルポリシーにauthenticatedを許可。
-- Insert ー＞　Auth　Select -> AnonとAuth 

-- Thinksテーブルのポリシー編集
alter policy "Allow anonymous inserts"
    on public.thinks
        to authenticated
        with check (true);

alter policy "Allow anonymous reads"
    on public.thinks
        to anon, authenticated
        using(true);

-- Repliesテーブルのポリシー編集
alter policy "Allow anonymous inserts"
    on public.replies
        to authenticated
        with check(true);

alter policy "Allow anonymous reads"
    on public.replies
        to anon, authenticated
        using(true);

-- Knowledgeテーブルのポリシー編集
alter policy "Allow anonymous knowledge inserts"
    on public.knowledge
        to authenticated
        with check(true);

alter policy "Allow anonymous knowledge select"
    on public.knowledge
        to anon, authenticated
        using(true);

alter policy "Allow anonymous knowledge update"
    on public.knowledge
        to authenticated
        with check(true);

-- 第六次テスト、各自テーブルの引数追加
-- thinksテーブルで引数追加
alter table public.thinks
    add column if not exists user_id uuid
        references auth.users(id) on delete cascade,
    add column if not exists is_public boolean
        not null default true;

-- repliesテーブルで引数追加
alter table public.replies
    add column if not exists user_id uuid 
        references auth.users(id) on delete cascade;


-- 第7次テスト、各自テーブル・ポリシー追加

-- thinksテーブルにuser_id用のポリシー作成
alter policy "Allow anonymous inserts" on public.thinks
    to  authenticated
    with check(
        (select auth.uid()) = user_id
    );

alter policy "Allow anonymous reads" on public.thinks
    to anon, authenticated
    using(
        is_public = true 
         or user_id = (select auth.uid())
    );

-- repliesテーブルにuser_id用のポリシー作成

alter policy "Allow anonymous inserts" on public.replies
    to authenticated
    with check(
        (select auth.uid()) = replies.user_id
        
        and

        exists (
            select 1
            from public.thinks as think
            where think.id = replies.think_id
                and (
                    think.is_public = true
                    or think.user_id = (select auth.uid())
                )
        )
    );

alter policy "Allow anonymous reads" on public.replies
    to anon, authenticated
    using(
        exists (
            select 1
            from public.thinks as think
            where think.id = replies.think_id
                and (
                    think.is_public = true
                    or think.user_id = (select auth.uid())
                )
        )
    );

-- Knowledgeテーブル
alter policy "Allow anonymous knowledge inserts" on public.knowledge
    to authenticated
    with check(
        exists(
            select 1 
            from public.thinks as think
            where think.id = knowledge.think_id
                and think.user_id = (select auth.uid())
        )
    );

alter policy "Allow anonymous knowledge select" on public.knowledge
    to anon, authenticated
    using(
        exists (
            select 1
            from public.thinks as think
            where think.id = knowledge.think_id
                and (
                    think.is_public = true
                    or think.user_id = (select auth.uid())
                )
        )
    );

alter policy "Allow anonymous knowledge update" on public.knowledge
    to authenticated
    using(
        exists(
            select 1
            from public.thinks as think
            where think.id = knowledge.think_id
                and think.user_id = (select auth.uid())
        )
    )
    with check(
        exists(
            select 1
            from public.thinks as think
            where think.id = knowledge.think_id
                and think.user_id = (select auth.uid())
        )
    );


-- thinks・repliesテーブルのuser_idに権限追加
-- 今の設定だと、user_idにauth.uid()が自動設定されない。

-- --　一旦、user_idの既存データを削除する。
-- delete from public.thinks  where user_id is null;
-- delete from public.replies where user_id is null;

-- thinksテーブルのuser_idにauth.uid()をデフォで追加させる。
alter table public.thinks
    alter column user_id set default auth.uid(),
    alter column user_id set not null;

-- repliesテーブルも同様に
alter table public.replies
    alter column user_id set default auth.uid(),
    alter column user_id set not null;


-- 第7次テスト/pgvector有効化とthinks.embedding追加
-- pgvectorが使用するスキーマ
create schema if not exists extensions;

-- pgvectorを有効化
create extension if not exists vector
    with schema extensions;

-- Thinkに256次元のEmbedingを保持できるようにする
alter table public.thinks
    add column if not exists embedding extensions.vector(256);

comment on column public.thinks.embedding is 
    'voyage-4-liteで生成した256次元のEmbedding';

-- 第８次テスト
-- 旧Embedding受け渡し方式のRPCの削除
drop function if exists public.match_thinks(
    extensions.vector,
    uuid,
    integer
);

create or replace function public.match_thinks(
    source_think_id uuid,
    match_count integer default 3,
    match_threshold double precision default 0.0
)

returns table (
    id uuid,
    text text,
    similarity double precision
)

language sql
stable
security invoker
set search_path = public, extensions
as $$
    with source_think as (
        select source.embedding
        from public.thinks as source
        where source.id = source_think_id
            and source.embedding is not null
    )
    select 
        candidate.id,
        candidate.text,
        1 - (
            candidate.embedding <=> source_think.embedding
        ) as similarity
    from public.thinks as candidate
    cross join source_think
    where candidate.id <> source_think_id
        and candidate.embedding is not null
        and 1 - (
            candidate.embedding <=> source_think.embedding
        ) >= coalesce(match_threshold, 0.0)
    order by candidate.embedding <=> source_think.embedding
    limit least(
        greatest(coalesce(match_count, 3), 1),
        20
    );
$$;

comment on function public.match_thinks(
    uuid,
    integer,
    double precision
) is 
    'Think IDを受け取り、RLSで閲覧可能なThinkからコサイン類似度順に返す';

revoke all 
on function public.match_thinks(
    uuid, 
    integer,
    double precision
) from public;

grant execute
on function public.match_thinks(
    uuid,
    integer,
    double precision
) to anon, authenticated;

-- DISTILL（会話の蒸留）の非公開キャッシュ、ロック、利用回数制限
create table public.distill_runs (
    id uuid primary key default gen_random_uuid(),
    think_id uuid not null references public.thinks(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    input_hash text not null check (input_hash ~ '^[0-9a-f]{64}$'),
    reply_count integer not null check (reply_count between 1 and 100),
    last_reply_at timestamptz not null,
    status text not null check (status in ('processing', 'completed', 'failed')),
    summary text,
    common_points text,
    disagreements text,
    open_questions text,
    model text not null,
    lease_token uuid,
    lease_expires_at timestamptz,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    constraint distill_runs_think_id_input_hash_key unique (think_id, input_hash),
    constraint distill_runs_completed_result_check check (
        status <> 'completed'
        or (
            summary is not null
            and common_points is not null
            and disagreements is not null
            and open_questions is not null
            and completed_at is not null
        )
    )
);

create index distill_runs_user_id_created_at_idx
    on public.distill_runs (user_id, created_at desc);

create index distill_runs_think_id_completed_at_idx
    on public.distill_runs (think_id, completed_at desc)
    where status = 'completed';

create table public.distill_usage_events (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    think_id uuid not null references public.thinks(id) on delete cascade,
    distill_run_id uuid not null references public.distill_runs(id) on delete cascade,
    status text not null check (status in ('started', 'completed', 'failed')),
    created_at timestamptz not null default now()
);

create index distill_usage_events_user_id_created_at_idx
    on public.distill_usage_events (user_id, created_at desc);

create index distill_usage_events_think_id_created_at_idx
    on public.distill_usage_events (think_id, created_at desc);

alter table public.distill_runs enable row level security;
alter table public.distill_usage_events enable row level security;

revoke all on table public.distill_runs from anon, authenticated;
revoke all on table public.distill_usage_events from anon, authenticated;

create or replace function public.acquire_distill_run(
    p_think_id uuid,
    p_user_id uuid,
    p_input_hash text,
    p_reply_count integer,
    p_last_reply_at timestamptz,
    p_model text,
    p_cooldown_minutes integer,
    p_daily_limit integer,
    p_lock_minutes integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_now timestamptz := clock_timestamp();
    v_run public.distill_runs%rowtype;
    v_usage_event_id uuid;
    v_lease_token uuid := pg_catalog.gen_random_uuid();
    v_daily_count integer;
    v_daily_oldest timestamptz;
    v_last_think_usage timestamptz;
    v_retry_after integer;
begin
    if p_input_hash !~ '^[0-9a-f]{64}$'
        or p_reply_count not between 1 and 100
        or p_last_reply_at is null
        or nullif(trim(p_model), '') is null
        or p_cooldown_minutes not between 1 and 1440
        or p_daily_limit not between 1 and 1000
        or p_lock_minutes not between 1 and 60 then
        return jsonb_build_object('action', 'invalid_request');
    end if;

    if not exists (
        select 1
        from public.thinks as think
        where think.id = p_think_id
          and think.user_id = p_user_id
    ) then
        return jsonb_build_object('action', 'forbidden');
    end if;

    -- Always acquire these in the same order. This makes limit checks and the
    -- usage reservation atomic even for two different inputs from one user.
    perform pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended('distill:user:' || p_user_id::text, 0)
    );
    perform pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended('distill:think:' || p_think_id::text, 0)
    );

    select *
      into v_run
      from public.distill_runs
     where think_id = p_think_id
       and input_hash = p_input_hash
     for update;

    if found and v_run.status = 'completed' then
        return jsonb_build_object(
            'action', 'cached',
            'run_id', v_run.id,
            'summary', v_run.summary,
            'common_points', v_run.common_points,
            'disagreements', v_run.disagreements,
            'open_questions', v_run.open_questions,
            'reply_count', v_run.reply_count,
            'generated_at', v_run.completed_at
        );
    end if;

    if found
       and v_run.status = 'processing'
       and v_run.lease_expires_at > v_now then
        v_retry_after := greatest(
            1,
            ceil(extract(epoch from (v_run.lease_expires_at - v_now)))::integer
        );
        return jsonb_build_object(
            'action', 'in_progress',
            'retry_after_seconds', least(v_retry_after, 10)
        );
    end if;

    select count(*)::integer, min(created_at)
      into v_daily_count, v_daily_oldest
      from public.distill_usage_events
     where user_id = p_user_id
       and created_at > v_now - interval '24 hours';

    if v_daily_count >= p_daily_limit then
        v_retry_after := greatest(
            1,
            ceil(extract(epoch from (
                v_daily_oldest + interval '24 hours' - v_now
            )))::integer
        );
        return jsonb_build_object(
            'action', 'daily_limit',
            'retry_after_seconds', v_retry_after,
            'remaining_requests', 0
        );
    end if;

    select max(created_at)
      into v_last_think_usage
      from public.distill_usage_events
     where think_id = p_think_id
       and created_at > v_now - make_interval(mins => p_cooldown_minutes);

    if v_last_think_usage is not null then
        v_retry_after := greatest(
            1,
            ceil(extract(epoch from (
                v_last_think_usage
                + make_interval(mins => p_cooldown_minutes)
                - v_now
            )))::integer
        );
        return jsonb_build_object(
            'action', 'cooldown',
            'retry_after_seconds', v_retry_after,
            'remaining_requests', p_daily_limit - v_daily_count
        );
    end if;

    if v_run.id is null then
        insert into public.distill_runs (
            think_id,
            user_id,
            input_hash,
            reply_count,
            last_reply_at,
            status,
            model,
            lease_token,
            lease_expires_at,
            started_at
        ) values (
            p_think_id,
            p_user_id,
            p_input_hash,
            p_reply_count,
            p_last_reply_at,
            'processing',
            p_model,
            v_lease_token,
            v_now + make_interval(mins => p_lock_minutes),
            v_now
        )
        returning * into v_run;
    else
        update public.distill_runs
           set user_id = p_user_id,
               reply_count = p_reply_count,
               last_reply_at = p_last_reply_at,
               status = 'processing',
               summary = null,
               common_points = null,
               disagreements = null,
               open_questions = null,
               model = p_model,
               lease_token = v_lease_token,
               lease_expires_at = v_now + make_interval(mins => p_lock_minutes),
               started_at = v_now,
               completed_at = null
         where id = v_run.id
        returning * into v_run;
    end if;

    insert into public.distill_usage_events (
        user_id,
        think_id,
        distill_run_id,
        status,
        created_at
    ) values (
        p_user_id,
        p_think_id,
        v_run.id,
        'started',
        v_now
    )
    returning id into v_usage_event_id;

    return jsonb_build_object(
        'action', 'started',
        'run_id', v_run.id,
        'lease_token', v_lease_token,
        'usage_event_id', v_usage_event_id,
        'remaining_requests', p_daily_limit - v_daily_count - 1
    );
end;
$$;

revoke all on function public.acquire_distill_run(
    uuid,
    uuid,
    text,
    integer,
    timestamptz,
    text,
    integer,
    integer,
    integer
) from public, anon, authenticated;

grant execute on function public.acquire_distill_run(
    uuid,
    uuid,
    text,
    integer,
    timestamptz,
    text,
    integer,
    integer,
    integer
) to service_role;

create or replace function public.get_distill_status(p_think_id uuid)
returns table (
    reply_count integer,
    generated_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
    select run.reply_count, run.completed_at
      from public.distill_runs as run
      join public.thinks as think on think.id = run.think_id
     where run.think_id = p_think_id
       and run.status = 'completed'
       and think.user_id = (select auth.uid())
     order by run.completed_at desc
     limit 1;
$$;

revoke all on function public.get_distill_status(uuid) from public, anon;
grant execute on function public.get_distill_status(uuid) to authenticated;

comment on table public.distill_runs is
    'AI蒸留下書きの非公開キャッシュと同時実行ロック。公開Knowledgeとは分離する。';

comment on table public.distill_usage_events is
    'Anthropic API呼び出しを開始する処理の利用記録。失敗も保持する。';

-- CONNECT（関連Think）のJev判定キャッシュと同時実行ロック
create table public.related_think_runs (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    source_think_id uuid not null references public.thinks(id) on delete cascade,
    input_hash text not null check (input_hash ~ '^[0-9a-f]{64}$'),
    status text not null check (status in ('processing', 'completed', 'failed')),
    scores jsonb,
    model text not null,
    prompt_version text not null,
    lease_token uuid,
    lease_expires_at timestamptz,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    constraint related_think_runs_cache_key unique (
        user_id,
        source_think_id,
        input_hash
    ),
    constraint related_think_runs_completed_scores_check check (
        status <> 'completed'
        or (
            scores is not null
            and
            jsonb_typeof(scores) = 'array'
            and completed_at is not null
        )
    ),
    constraint related_think_runs_processing_lease_check check (
        status <> 'processing'
        or (
            lease_token is not null
            and lease_expires_at is not null
        )
    )
);

alter table public.related_think_runs enable row level security;

-- CONNECTキャッシュはEdge Function専用。ブラウザから直接読み書きさせない。
revoke all on table public.related_think_runs from anon, authenticated;

create or replace function public.acquire_related_think_run(
    p_user_id uuid,
    p_source_think_id uuid,
    p_input_hash text,
    p_model text,
    p_prompt_version text,
    p_lock_minutes integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_now timestamptz := clock_timestamp();
    v_run public.related_think_runs%rowtype;
    v_lease_token uuid := pg_catalog.gen_random_uuid();
    v_retry_after integer;
begin
    if p_input_hash !~ '^[0-9a-f]{64}$'
        or nullif(pg_catalog.btrim(p_model), '') is null
        or nullif(pg_catalog.btrim(p_prompt_version), '') is null
        or p_lock_minutes not between 1 and 10 then
        return jsonb_build_object('action', 'invalid_request');
    end if;

    if not exists (
        select 1
        from public.thinks as think
        where think.id = p_source_think_id
          and (
              think.is_public = true
              or think.user_id = p_user_id
          )
    ) then
        return jsonb_build_object('action', 'forbidden');
    end if;

    perform pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(
            'connect:'
            || p_user_id::text
            || ':'
            || p_source_think_id::text
            || ':'
            || p_input_hash,
            0
        )
    );

    select *
      into v_run
      from public.related_think_runs
     where user_id = p_user_id
       and source_think_id = p_source_think_id
       and input_hash = p_input_hash
     for update;

    if found and v_run.status = 'completed' then
        return jsonb_build_object(
            'action', 'cached',
            'run_id', v_run.id,
            'scores', v_run.scores,
            'model', v_run.model,
            'generated_at', v_run.completed_at
        );
    end if;

    if found
       and v_run.status = 'processing'
       and v_run.lease_expires_at > v_now then
        v_retry_after := greatest(
            1,
            ceil(extract(epoch from (v_run.lease_expires_at - v_now)))::integer
        );

        return jsonb_build_object(
            'action', 'in_progress',
            'retry_after_seconds', least(v_retry_after, 10)
        );
    end if;

    if v_run.id is null then
        insert into public.related_think_runs (
            user_id,
            source_think_id,
            input_hash,
            status,
            scores,
            model,
            prompt_version,
            lease_token,
            lease_expires_at,
            started_at
        ) values (
            p_user_id,
            p_source_think_id,
            p_input_hash,
            'processing',
            null,
            p_model,
            p_prompt_version,
            v_lease_token,
            v_now + make_interval(mins => p_lock_minutes),
            v_now
        )
        returning * into v_run;
    else
        update public.related_think_runs
           set status = 'processing',
               scores = null,
               model = p_model,
               prompt_version = p_prompt_version,
               lease_token = v_lease_token,
               lease_expires_at = v_now + make_interval(mins => p_lock_minutes),
               started_at = v_now,
               completed_at = null
         where id = v_run.id
        returning * into v_run;
    end if;

    return jsonb_build_object(
        'action', 'started',
        'run_id', v_run.id,
        'lease_token', v_lease_token
    );
end;
$$;

revoke all on function public.acquire_related_think_run(
    uuid,
    uuid,
    text,
    text,
    text,
    integer
) from public, anon, authenticated;

grant execute on function public.acquire_related_think_run(
    uuid,
    uuid,
    text,
    text,
    text,
    integer
) to service_role;

comment on table public.related_think_runs is
    'ユーザー別のJev関連判定キャッシュと同時実行リース。本文は保存しない。';
