-- 第一次テスト、名無しユーザでもinsert可能に
alter table public.thinks enable row level security;
create policy "Allow anonymous inserts"on public.thinks
  for insert
    to anon
    with check (true)
-- 第二次テスト、名無しユーザでもselect可能に
create policy "Allow anonymous reads"
on public.thinks
    for select
    to anon
    using (true)

-- 第三次テスト、Discuss用のテーブルrepliesテーブルを追加
create table public.replies (
    id bigint generated by default as identity primary key,
    think_id uuid not null references public.thinks(id) on delete cascade,
    text text not null
        check (char_length(trim(text)) > 0),
    created_at timestamptz not null default now()
);

create index replies_think_id_created_at_idx
    on public.replies (think_id, created_at);
alter table public.replies enable row level security;

create policy "Allow anonymous inserts" on public.replies
    for insert
        to anon
        with check (true);

create policy "Allow anonymous reads" on public.replies
    for select
        to anon
        using (true);